[package]
name = "ios"
version = "0.1.0"
edition = "2024"

[lib]
name = "pdfnative"
crate-type = ["staticlib"]

[dependencies]
pdf-core = { path = "../core" }
objc2 = "0.6.1"
objc2-foundation = { version = "0.3.1", features = ["NSData"]}