[package]
name = "pdf-core"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.4"
image = "0.25"
byteorder = "1"


[target.'cfg(target_os = "ios")'.dependencies]
pdfium-render = { git = "https://github.com/ajrcarey/pdfium-render", rev = "9a051c3c4c1683e15fc3a435a58107babf85e6c3", features = ["image_025", "pdfium_7215", "thread_safe", "static", "paragraph"] }

[target.'cfg(not(target_os = "ios"))'.dependencies]
pdfium-render = { git = "https://github.com/ajrcarey/pdfium-render", rev = "9a051c3c4c1683e15fc3a435a58107babf85e6c3", features = ["image_025", "pdfium_7215", "thread_safe", "paragraph"] }