#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "pdf_core.h"

typedef struct CPdfNative CPdfNative;

typedef struct CPdfNativeDocument CPdfNativeDocument;

typedef struct PdfNativeTextOptions PdfNativeTextOptions;

struct CPdfNative *pdf_native_init(void);

void pdf_native_release(struct CPdfNative *instance);

struct CPdfNativeDocument *pdf_native_load_from_path(struct CPdfNative *instance,
                                                     const char *path,
                                                     const char *password);

struct CPdfNativeDocument *pdf_native_load_from_bytes(struct CPdfNative *instance,
                                                      const uint8_t *buffer,
                                                      uintptr_t size,
                                                      const char *password);

struct CPdfNativeDocument *pdf_native_document_init(struct CPdfNative *instance,
                                                    const PdfNativeDocumentConfig *config);

void pdf_native_document_release(struct CPdfNative *instance);

int pdf_native_document_count(struct CPdfNativeDocument *instance);

float pdf_native_document_width(struct CPdfNativeDocument *instance);

float pdf_native_document_height(struct CPdfNativeDocument *instance);

unsigned int pdf_native_document_current_page(struct CPdfNativeDocument *instance);

void pdf_native_document_add_page(struct CPdfNativeDocument *instance,
                                  PdfNativePaperSize size,
                                  PdfNativeOrientation orientation);

void pdf_native_document_circle(struct CPdfNativeDocument *instance,
                                float x,
                                float y,
                                float r,
                                PdfNativeStyle style);

void pdf_native_document_ellipse(struct CPdfNativeDocument *instance,
                                 float x,
                                 float y,
                                 float rx,
                                 float ry,
                                 PdfNativeStyle style);

void pdf_native_document_rect(struct CPdfNativeDocument *instance,
                              float x,
                              float y,
                              float width,
                              float height,
                              PdfNativeStyle style);

void pdf_native_document_rounded_rect(struct CPdfNativeDocument *instance,
                                      float x,
                                      float y,
                                      float width,
                                      float height,
                                      float rx,
                                      float ry,
                                      PdfNativeStyle style);

void pdf_native_document_delete_page(struct CPdfNativeDocument *instance, unsigned int index);

void pdf_native_document_set_page(struct CPdfNativeDocument *instance, unsigned int index);

void pdf_native_document_set_font_size(struct CPdfNativeDocument *instance, float size);

float pdf_native_document_get_font_size(struct CPdfNativeDocument *instance);

void pdf_native_document_set_font_color(struct CPdfNativeDocument *instance,
                                        int32_t r,
                                        int32_t g,
                                        int32_t b,
                                        int32_t a);

void pdf_native_document_set_draw_color(struct CPdfNativeDocument *instance,
                                        int32_t r,
                                        int32_t g,
                                        int32_t b,
                                        int32_t a);

void pdf_native_document_set_fill_color(struct CPdfNativeDocument *instance,
                                        int32_t r,
                                        int32_t g,
                                        int32_t b,
                                        int32_t a);

void pdf_native_document_set_line_width(struct CPdfNativeDocument *instance, float width);

float pdf_native_document_get_line_width(struct CPdfNativeDocument *instance);

void pdf_native_document_add_text(struct CPdfNativeDocument *instance,
                                  const char *text,
                                  float x,
                                  float y,
                                  const PdfNativeTextOptions *options);

void pdf_native_document_add_text_matrix(struct CPdfNativeDocument *instance,
                                         const char *text,
                                         float x,
                                         float y,
                                         const PdfNativeTextOptions *options,
                                         float a,
                                         float b,
                                         float c,
                                         float d,
                                         float e,
                                         float f);

void pdf_native_document_add_image(struct CPdfNativeDocument *instance,
                                   const uint8_t *image_data,
                                   unsigned int image_size,
                                   float x,
                                   float y,
                                   int32_t width,
                                   int32_t height);

void pdf_native_document_table(struct CPdfNativeDocument *instance, const CPdfTable *config);

void pdf_native_document_render_to_buffer(struct CPdfNativeDocument *instance,
                                          int index,
                                          unsigned int width,
                                          unsigned int height,
                                          uint8_t *buffer,
                                          uintptr_t size);

void pdf_native_document_render_with_buffer_size(struct CPdfNativeDocument *instance,
                                                 int index,
                                                 uint8_t *buffer,
                                                 uintptr_t size,
                                                 float viewport_width,
                                                 float viewport_height,
                                                 float scale_x,
                                                 float scale_y,
                                                 float x,
                                                 float y,
                                                 float width,
                                                 float height,
                                                 float scaled_x,
                                                 float scaled_y,
                                                 float scaled_width,
                                                 float scaled_height);

