[package]
name = "android"
version = "0.1.0"
edition = "2024"


[lib]
name = "pdfnative"
crate-type = ["cdylib"]

[dependencies]
pdf-core = { path = "../core" }
jni = "0.21.1"
ndk = {version = "0.7.0", features = ["bitmap"]}
once_cell = "1.21.3"
log = "0.4.27"
android_logger = "0.14.1"